{% set name = "auto-intersphinx" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e15da72d506f3cc3f2ffeb6a0231dfb57a6d51da4551530cac717d34d408af87

build:
  entry_points:
    - auto-intersphinx = auto_intersphinx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - versioningit
    - pip
  run:
    - python >=3.10
    - sphinx
    - packaging
    - requests
    - lxml

test:
  source_files:
    - tests
  imports:
    - auto_intersphinx
  commands:
    - pip check
    - auto-intersphinx --help
    - pytest -sv tests
  requires:
    - pip
    - pytest

about:
  home: https://gitlab.idiap.ch/software/auto-intersphinx
  doc_url: https://auto-intersphinx.readthedocs.io
  dev_url: https://gitlab.idiap.ch/software/auto-intersphinx
  summary: Automatic links direct project dependencies to the intersphinx catalog
  license: BSD-3-Clause
  license_file: LICENSES/BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - anjos
